package design

import (
	_ "goaviron/design/resources/aikatsu"
	_ "goaviron/design/resources/viron"
	"goaviron/env"

	. "github.com/goadesign/goa/design"
	. "github.com/goadesign/goa/design/apidsl"
)

var _ = API("goaviron", func() {
	Title("goaviron")
	Description("goa + vironの可能性を探る")
	Version("1.0")
	Contact(func() {
		Name("romiogaku")
		Email("romiogaku@me.com")
	})
	Host(env.Server.APIHostStringOnDoc())
	Scheme("http")
	BasePath("")
	Consumes("application/json") // Media types supported by the API
	Produces("application/json") // Media types generated by the API
})
